version: '3.7'

networks:
  scraper-net:
    driver: bridge
    external: true

services:
  tokopedia-scraper:
    image: tokopedia-scraper:1.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tokopedia-scraper
    restart: always
    networks:
      - scraper-net