version: '3.7'

networks:
  scraper-net:
    driver: bridge
    external: true

services:
  lazada-scraper:
    image: lazada-scraper:1.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: lazada-scraper
    restart: always
    networks:
      - scraper-net